//
//  SampleData.swift
//  LineChartWithPagination
//
//  Created by Mit Shah on 04/01/22.
//

import Foundation
extension SomeEntity {
static let sampleDataSet1 = [SomeEntity(count: 1, amount: 10),
                             SomeEntity(count: 29, amount: 1414),
                             SomeEntity(count: 36, amount: 2893),
                             SomeEntity(count: 74, amount: 7661),
                             SomeEntity(count: 37, amount: 5089),
                             SomeEntity(count: 67, amount: 11054),
                             SomeEntity(count: 45, amount: 8916),
                             SomeEntity(count: 42, amount: 9518),
                             SomeEntity(count: 38, amount: 9724),
                             SomeEntity(count: 18, amount: 5133),
                             SomeEntity(count: 18, amount: 5645),
                             SomeEntity(count: 23, amount: 7954),
                             SomeEntity(count: 10, amount: 3748),
                             SomeEntity(count: 13, amount: 5223),
                             SomeEntity(count: 3, amount: 1295),
                             SomeEntity(count: 5, amount: 2315),
                             SomeEntity(count: 3, amount: 1467),
                             SomeEntity(count: 4, amount: 2110),
                             SomeEntity(count: 4, amount: 2233),
                             SomeEntity(count: 2, amount: 1163),
                             SomeEntity(count: 1, amount: 638),
                             SomeEntity(count: 1, amount: 749),
                             SomeEntity(count: 1, amount: 787),
                             SomeEntity(count: 0, amount: 0),
                             SomeEntity(count: 0, amount: 0),
                             SomeEntity(count: 0, amount: 0),
                             SomeEntity(count: 0, amount: 0),
                             SomeEntity(count: 0, amount: 0),
                             SomeEntity(count: 0, amount: 0),
                             SomeEntity(count: 0, amount: 0)]
    
static let sampleDataSet2 = [SomeEntity(count: 0, amount: 0),
                             SomeEntity(count: 1, amount: 55),
                             SomeEntity(count: 1, amount: 84),
                             SomeEntity(count: 7, amount: 795),
                             SomeEntity(count: 8, amount: 1048),
                             SomeEntity(count: 3, amount: 485),
                             SomeEntity(count: 10, amount: 1937),
                             SomeEntity(count: 9, amount: 2040),
                             SomeEntity(count: 10, amount: 2575),
                             SomeEntity(count: 10, amount: 2866),
                             SomeEntity(count: 6, amount: 1890),
                             SomeEntity(count: 7, amount: 2424),
                             SomeEntity(count: 7, amount: 2819),
                             SomeEntity(count: 5, amount: 2181),
                             SomeEntity(count: 4, amount: 1871),
                             SomeEntity(count: 1, amount: 506),
                             SomeEntity(count: 4, amount: 2087),
                             SomeEntity(count: 2, amount: 1118),
                             SomeEntity(count: 1, amount: 585),
                             SomeEntity(count: 3, amount: 1836),
                             SomeEntity(count: 1, amount: 634),
                             SomeEntity(count: 2, amount: 1329),
                             SomeEntity(count: 3, amount: 2121),
                             SomeEntity(count: 1, amount: 723),
                             SomeEntity(count: 2, amount: 1888),
                             SomeEntity(count: 1, amount: 980),
                             SomeEntity(count: 2, amount: 2054),
                             SomeEntity(count: 1, amount: 1172),
                             SomeEntity(count: 0, amount: 0),
                             SomeEntity(count: 0, amount: 0)]
}
